stages:
  - external-build
  - build-wait
  - test
  - qa-deploy
  - prod-deploy

.sqa-connection: &sqa-connection
  tags:
    - host_network
  secrets: &testnet-secrets
    TESTNET_CERT:
      vault: corp/build/gltest-testnet/crt@secret
      file: true
    TESTNET_KEY:
      vault: corp/build/gltest-testnet/key@secret
      file: true

.ci-deploy-connection: &ci-deploy-connection
  tags:
    - cap_sys_admin
  secrets:
    <<: *testnet-secrets
    CI_DEPLOY_KEY:
      vault: corp/build/hello-ci-ed/key@secret
      file: true
    CI_DEPLOY_PUB_KEY:
      vault: corp/build/hello-ci-ed/pub@secret
      file: true

.cd-deploy-connection: &cd-deploy-connection
  tags:
    - cap_sys_admin
  secrets:
    <<: *testnet-secrets
    CI_DEPLOY_KEY:
      vault: corp/build/hello-cd-ed/key@secret
      file: true
    CI_DEPLOY_PUB_KEY:
      vault: corp/build/hello-cd-ed/pub@secret
      file: true

.external-build-job:
  <<: *sqa-connection
  stage: external-build
  image: docker.io/alpine
  script:
    - apk add --update --no-cache dash openssl jq curl
    - dash job_scripts/queue-event.sh
  artifacts:
    paths:
      - artifacts/event_id.txt

.wait-for-completion:
  <<: *sqa-connection
  stage: build-wait
  image: docker.io/alpine
  script:
    - apk add --update --no-cache bash openssl jq curl
    - bash job_scripts/wait-for-job.sh
  artifacts:
    paths:
      - artifacts/sourcejob_id.txt
      - artifacts/job_id.txt

.scan-job:
  <<: *sqa-connection
  stage: test
  image:
    name: quay.io/skopeo/stable:latest
    entrypoint: [""]
  script:
    - bash job_scripts/upload-for-scan.sh

deploy-ci-job:
  <<: *ci-deploy-connection
  stage: qa-deploy
  environment:
    name: QA
    url: https://hello-ci.akamai.lol
  image:
    name: quay.io/podman/stable:v3.4.4
    entrypoint: [""]
  variables:
    PODMAN_USER: "ci-user"
    PODMAN_UID: "1000"
  script:
    - bash job_scripts/deploy.sh

deploy-ci-job:
  <<: *cd-deploy-connection
  stage: qa-deploy
  environment:
    name: PROD
    url: https://hello-cd.akamai.lol
  when: manual
  image:
    name: quay.io/podman/stable:v3.4.4
    entrypoint: [""]
  variables:
    PODMAN_USER: "cd-user"
    PODMAN_UID: "1001"
  script:
    - bash job_scripts/deploy.sh