.project-registry-login: &project-registry-login
  before_script:
    - echo -e "[[registry]]\nlocation = \"$CI_REGISTRY\"\ninsecure = true" > /etc/containers/registries.conf.d/ci.conf
    - podman login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

.sqa-connection: &sqa-connection
  secrets: &testnet-secrets
    TESTNET_CERT:
      vault: corp/build/bbodiya/crt@secret
      file: true
    TESTNET_KEY:
      vault: corp/build/bbodiya/key@secret
      file: true

.deploy-common: &deploy-common
  image:
    name: quay.io/podman/stable:v3.4.4
    entrypoint: [""]
  tags:
    - cap_sys_admin

.linode-QA-deploy-connection: &linode-QA-deploy-connection
  <<: *deploy-common
  secrets:
    CI_DEPLOY_KEY:
      vault: corp/build/hello-ci-ed/key@secret
      file: true

.linode-PROD-deploy-connection: &linode-PROD-deploy-connection
  <<: *deploy-common
  secrets:
    <<: *testnet-secrets
    CI_DEPLOY_KEY:
      vault: corp/build/hello-cd-ed/key@secret
      file: true

.k8s-QA-deploy-connection: &k8s-QA-deploy-connection
  <<: *deploy-common
  secrets:
    K8S_REGISTRY_USER:
      vault: corp/build/k8s-registry/user@secret
      file: false
    K8S_REGISTRY_PASSWORD:
      vault: corp/build/k8s-registry/password@secret
      file: false
    K8S_KUBECONFIG:
      vault: corp/build/k8s-qa/kubeconfig@secret
      file: true

.k8s-PROD-deploy-connection: &k8s-PROD-deploy-connection
  <<: *deploy-common
  secrets:
    <<: *testnet-secrets
#TODO - move this to a different location to show secret separation
    K8S_REGISTRY_USER:
      vault: corp/build/k8s-registry/user@secret
      file: false
    K8S_REGISTRY_PASSWORD:
      vault: corp/build/k8s-registry/password@secret
      file: false
    K8S_KUBECONFIG:
      vault: corp/build/k8s-prod/kubeconfig@secret
      file: true