# Base layers for use with "extends:"
.deploy-common:
  image:
    name: quay.io/podman/stable:v3.4.4
    entrypoint: [""]
  tags:
    - cap_sys_admin

# Specific sub-section references for use with !reference
.project-registry-login:
  before_script:
    - echo -e "[[registry]]\nlocation = \"$CI_REGISTRY\"\ninsecure = true" > /etc/containers/registries.conf.d/ci.conf
    - podman login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

.k8s-registry-login:
  before_script:
    - podman login -u $K8S_REGISTRY_USER -p $K8S_REGISTRY_PASSWORD registry.linode.lol

.sqa-connection:
  secrets:
    TESTNET_CERT:
      vault: corp/build/bbodiya/crt@secret
      file: true
    TESTNET_KEY:
      vault: corp/build/bbodiya/key@secret
      file: true

.linode-QA-deploy-connection:
  secrets:
    CI_DEPLOY_KEY:
      vault: corp/build/hello-ci-ed/key@secret
      file: true

.linode-PROD-deploy-connection:
  secrets:
    - !reference [.sqa-connection, secrets]
    CI_DEPLOY_KEY:
      vault: corp/build/hello-cd-ed/key@secret
      file: true

.k8s-QA-deploy-connection:
  secrets:
    K8S_REGISTRY_USER:
      vault: corp/build/k8s-registry/user@secret
      file: false
    K8S_REGISTRY_PASSWORD:
      vault: corp/build/k8s-registry/password@secret
      file: false
    K8S_KUBECONFIG:
      vault: corp/build/k8s-qa/kubeconfig@secret
      file: true

.k8s-PROD-deploy-connection:
  secrets:
    - !reference [.sqa-connection, secrets]
#TODO - move this to a different location to show secret separation
    K8S_REGISTRY_USER:
      vault: corp/build/k8s-registry/user@secret
      file: false
    K8S_REGISTRY_PASSWORD:
      vault: corp/build/k8s-registry/password@secret
      file: false
    K8S_KUBECONFIG:
      vault: corp/build/k8s-prod/kubeconfig@secret
      file: true